03-objects-arrays-intro-to-testing
js-tasks-ru/js-20210806_galinam pull request #3
Opened 2021-08-16 13:40 UTC by galchk-m

2021-08-16 13:41 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-08-17 10:27 UTC, dosandk commented on .gitignore
> +/02-javascript-data-types/1-sort-strings/index.js
данных изменений не должно быт в PR. Локально можно менять все файлы, но вот добавлять что-то что не относиться к решению в PR категорически нельзя, это может повлиять на корректность работы задачника

2021-08-17 10:27 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  const fields = path.split('.');
👍 лайк за использования замыкания

2021-08-17 10:28 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  return (Obj) => fields.reduce((field, i) => field && field[i], Obj);
с заглавной буквы мы можем именовать только функции конструкторы и классы

2021-08-17 10:29 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +  return obj && Object.fromEntries(Object.entries(obj).map(([key, value]) => [value, key]));
good 👍

2021-08-17 10:30 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +  let counter = 0;
good 👍

2021-08-17 10:30 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return [...arr].reduce(
подумайте есть ли альтернативное решение, возможно с использованием `Set`?

2021-08-17 10:31 UTC, dosandk requested changes
решения приняты, посмотрите комментарии
изменения в `.gitignore` следует убрать из PR

2021-08-17 13:48 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-08-18 08:22 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-08-18 08:24 UTC, galchk-m commented
> решения приняты, посмотрите комментарии
> изменения в `.gitignore` следует убрать из PR

2021-08-18 08:25 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-08-18 19:42 UTC, dosandk approved these changes
good 👍

2021-08-18 19:42 UTC, merged